modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="twitch_intergration"
version="1.0.0"
displayName="twitch intergration"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net  --- mod maker web page"
authors="monsterT2008, Mcreator"
description='''
a intergration client for twitch
'''

[[dependencies.twitch_intergration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




